plugins {
    alias(libs.plugins.tableau.common)
    alias(libs.plugins.tableau.maven.publishing)
    id 'java-gradle-plugin'
}

repositories {
    mavenLocal()
    mavenCentral()
}

tableau {
    project {
        group = "com.communi-suggestu.scena"
        publisher = "communi-suggestu"
        versioning {
            version = environmentVariable("VERSION")
                    .orElse(property("local.version"))
            suffix = ""
        }
    }
    maven {
        publishUsingActionsTokenTo('maven', 'https://maven.communi-suggestu.com/repository/formatum-adhibe')
        publishLocally()
        pom({
            usingMitLicense()
            usingGit()
        })
    }
}

allprojects {Project project ->
    java {
        toolchain {
            languageVersion.set(JavaLanguageVersion.of(project.getProperties().get("java.version")))
        }
    }
}

dependencies {
    implementation 'dev.lukebemish:immaculate'
    implementation 'org.yaml:snakeyaml:2.2'

    testImplementation platform('org.junit:junit-bom:6.0.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation gradleTestKit()
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

gradlePlugin {
    plugins {
        formatumAdhibe {
            id = 'com.communi.suggestu.formatum.adhibe'
            implementationClass = 'com.communi.suggestu.formatum.adhibe.plugin.FormatumAdhibePlugin'
        }
    }
}

test {
    useJUnitPlatform()
}