pluginManagement {
    repositories {
        mavenLocal()
        maven {
            url 'https://ldtteam.jfrog.io/artifactory/communi-suggestu-maven'
            name 'Communi-Suggestu Maven'
        }
        maven {
            url 'https://ldtteam.jfrog.io/artifactory/tableau'
            name 'Tableau Maven'
        }
        gradlePluginPortal()
        mavenCentral()
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

rootProject.name = 'formatum-adhibe'