package com.communi.suggestu.formatum.adhibe.checkstyle.planning;

public enum GeneratedStepKind {
    ENSURE_TRAILING_NEWLINE,
    TRIM_TRAILING_WHITESPACE,
    COLLAPSE_CONSECUTIVE_BLANK_LINES,
    REMOVE_BLANK_LINE_AFTER_OPENING_BRACE,
    REMOVE_BLANK_LINE_BEFORE_CLOSING_BRACE,
    INSERT_BLANK_LINE_BEFORE_INDENTED_BLOCK,
    INSERT_BLANK_LINE_AFTER_INDENTED_BLOCK,
    LEFT_CURLY,
    RIGHT_CURLY,
    NEED_BRACES,
    EMPTY_LINE_SEPARATOR,
    OPERATOR_WRAP,
    SEPARATOR_WRAP,
    INDENTATION,
    PAREN_PAD,
    NO_WHITESPACE_BEFORE,
    NO_WHITESPACE_AFTER,
    WHITESPACE_AFTER,
    WHITESPACE_AROUND,
    SINGLE_SPACE_SEPARATOR,
    GENERIC_WHITESPACE,
    COMMENTS_INDENTATION,
    AVOID_STAR_IMPORT,
    ILLEGAL_IMPORT,
    REDUNDANT_IMPORT,
    UNUSED_IMPORT,
    CONVERT_LEADING_SPACES_TO_TABS,
    ORDER_IMPORTS
}

