name: Publish Maven

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Calculate semantic version
        id: semver
        uses: PaulHatch/semantic-version@v5.4.0
        with:
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          version_format: "${major}.${minor}.${patch}"
          bump_each_commit: false
          search_commit_body: true

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "25"

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Export version from semantic version
        run: echo "VERSION=${{ steps.semver.outputs.version }}" >> "$GITHUB_ENV"

      - name: Fetch OIDC token
        id: oidc
        run: |
          OIDC_JWT=$(curl -sS \
            -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=maven.communi-suggestu.com" \
            | jq -r .value)
          echo "token=$OIDC_JWT" >> $GITHUB_OUTPUT

      - name: Publish
        env:
          GITHUB_TOKEN: ${{ steps.oidc.outputs.token }}
          VERSION: ${{ env.VERSION }}
        run: ./gradlew --no-daemon publish --info --stacktrace

